version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - notes
    networks:
      - net

  backend:
    build: ./backend
    environment:
      - FLAG=AKASEC{CGI_is_fun}
      - FLAG_SECRET=e56ecf78991b116b8780dad70b7fb29614a279d4
    networks:
      - net

  notes:
    build: ./notes
    volumes:
      - ./notes/public:/var/www/html:ro
    networks:
      - net

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.13.12.0/27
